services:
  zotero:
    build:
      context: ./src
    ports:
      - "${PORT:-8888}:80"
    environment:
      - ZOTERO_USER=zotero
      - ZOTERO_PASS=zotero
    volumes:
      - ./data:/var/lib/dav/data
